spring:
  application.name: products
server:
  port: 8081
---
spring:
  profiles:
    active: user
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: dev
    password: password

  repository:
    type: hashmap
