spring:
  application.name: stores
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:./data/storesdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true